# Workflow name
name: Deploy to Firebase Hosting on push

# Triggers on every push to the `main` branch
on:
  push:
    branches:
      - main

# Defines the jobs
jobs:
  build_and_deploy:
    # Runs on the latest Ubuntu version
    runs-on: ubuntu-latest

    # Individual steps
    steps:
      # 1. Checks out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Node.js environment version 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Installs dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Builds the production version of the project
      - name: Build project
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}

      # 5. Deploys the built web app to Firebase Hosting using the Service Account
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ai-sensei-f2a05
